services:
  - type: web
    name: restaurante_v1_web
    plan: free
    runtime: python

    buildCommand: >
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py migrate --no-input &&
      python manage.py collectstatic --no-input

    startCommand: >
      gunicorn restaurante_v1.wsgi:application
      --bind 0.0.0.0:$PORT
      --workers ${WEB_CONCURRENCY:-4}
      --log-level info

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurante_v1db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: ".onrender.com"

      - key: WEB_CONCURRENCY
        value: "4"
