databases:
  - name: restaurante_v1db
    plan: free
    databaseName: restaurante
    user: mysite

services:
  - type: web
    plan: free
    name: restaurante_v1_web
    runtime: python
    buildCommand: >
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py migrate --no-input &&
      python manage.py collectstatic --no-input
    startCommand: 'gunicorn restaurante_v1.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurante_v1db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4